config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"

  root to: "products#index"
  get '/my_products', to: 'products#my_index', as: :my_products
  resources :products, only: [:destroy], as: :delete_products
  resources :products, except: [:destroy] do
    resources :bookmarks, only: [:new, :create] #maybe destroy?

  end
  resources :bookings, only: [:new, :create, :destroy, :edit, :index]
  resources :users, only: [:index] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:index]
    resources :bookmarks, only: [:destroy], as: :delete_bookmarks
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews

  validates :sexe, presence: true
  validates :couleurs, presence: true
  validates :textile_type, presence: true
  validates :category, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 6 }
  validates :availability, inclusion: { in: [true, false] }

  after_initialize :set_default_availability

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [ :title, :description ],
  using: {
    tsearch: { prefix: true }
  }

  scope :filter_by_size, ->(size) { where(size: size) if size.present? }
  scope :filter_by_category, ->(category) { where(category: category) if category.present? }
  scope :filter_by_sexe, ->(sexe) { where(sexe: sexe) if sexe.present? }
  scope :filter_by_couleurs, ->(couleurs) { where(couleurs: couleurs) if couleurs.present? }
  scope :filter_by_textile_type, ->(textile_type) { where(textile_type: textile_type) if textile_type.present? }


  private

  def set_default_availability
    self.availability ||= true if new_record?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @products = Product.search_by_title_and_description(params[:query])
    else
      @products = Product.all
      @products = @products.filter_by_sexe(params[:sexe]) if params[:sexe].present?
      @products = @products.filter_by_category(params[:category]) if params[:category].present?
      @products = @products.filter_by_size(params[:size]) if params[:size].present?
      @products = @products.filter_by_couleurs(params[:couleurs]) if params[:couleurs].present?
      @products = @products.filter_by_textile_type(params[:textile_type]) if params[:textile_type].present?
    end
  end

  def my_index
    @products = Product.where(user_id: current_user.id)
  end

  def show
    @product = Product.find_by(id: params[:id])
    @booking = Booking.new

    if @product.nil?
      redirect_to products_path, notice: "Product not found."
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(set_params)
    @product.user = current_user
    if @product.save
      redirect_to products_path, notice: "Product created successfully."
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find_by(id: params[:id])

    if @product.nil?
      redirect_to products_url, notice: "Product not found."
    end
  end

  def update
    @product = Product.find_by(id: params[:id])
    @product.update(set_params)

    if @product.save
      redirect_to products_url, notice: "Product updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy

    redirect_to products_url, notice: "Product deleted."
  end

  private

  def set_params
    params.require(:product).permit(:title, :category, :size, :price, :description, :availability, :user_id, :couleurs, :sexe, :textile_type,)
  end

end

app/views/products/_booking-form.html.erb
<%= simple_form_for @booking do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="text-center d-flex justify-content-center">
<%= form.input :start_date, label: "Début de la location",
            as: :string,
            input_html: { data: { controller: "datepicker" }, class: "field_style", } %>
                  </div>
    </div>
    <div class="col-6">
<%= form.input :end_date, label: "Fin de la location",
            as: :string,
            input_html: { data: { controller: "datepicker" }, class: "field_style", } %>
            </div>
            </div>
<%= form.hidden_field :product_id, value: params[:id] %>
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="text-center d-flex justify-content-center">
  <%= form.button :submit, "Réserver", class: "resa-button" %>
      </div>
    </div>
  </div>

<% end %>

app/views/products/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3000">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "placeholder.jpg", class: "d-block w-100"  %>
    </div>
    <div class="carousel-item">
      <%= image_tag "placeholder.jpg", class: "d-block w-100"  %>
    </div>
    <div class="carousel-item">
      <%= image_tag "placeholder.jpg", class: "d-block w-100"  %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/edit.html.erb
<div id="edit_container" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="text-center">
        <%= simple_form_for @product, url: product_path(@product), html: { class: "mt-3" } do |form| %>
          <div class="row">
            <%= form.input :title, label: "Titre" %>
            <%= form.input :description, label: "Description" %>
            <%= form.input :price, label: "Prix" %>
            <%= form.input :category, label: "Catégorie" do %>
                <%= form.collection_select :category, ['Sport', 'Déguisement', 'Pantalon', 'Jupe', 'Robe', 'Costume', 'Manteau', 'Autre'], :to_s, :to_s, prompt: 'Sélectionner une catégorie' %>
  <% end %>
            <%= form.input :size, label: "Taille" do %>
              <%= form.collection_select :size, %w[XS S M L XL XXL XXXL], :to_s, :to_s, prompt: 'Sélectionner une taille' %>
            <% end %>
              
  <%= form.input :sexe, label: "Genre" do %>
    <%= form.collection_select :sexe, ['Homme', 'Femme', 'Enfant'], :to_s, :to_s, prompt: 'Sélectionner un genre' %>
  <% end %>
  <%= form.input :couleurs do %>
    <%= form.collection_select :couleurs, %w[Rouge Bleu Jaune Vert Blanc Noir Gris Autre], :to_s, :to_s, prompt: 'Sélectionner une couleur' %>
  <% end %>
  <%= form.input :textile_type, label: "Matière" do %>
    <%= form.collection_select :textile_type, %w[Laine Coton Soie Lin Synthétique Plastique Acier Autre], :to_s, :to_s, prompt: 'Sélectionner un type de textile' %>
  <% end %>
            <div class="col-12">
              <%= form.button :submit, "Modifier votre produit", class: "resa-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="selected-list">

  <%= form_tag(products_path, method: :get, class: "mt-3") do %>
    <%= select_tag :sexe, options_for_select(['Homme', 'Femme', 'Enfant'], params[:sexe]), include_blank: 'Sélectionner un genre', class: 'color-input' %>
    <%= select_tag :category, options_for_select(['Sport', 'Déguisement', 'Pantalon', 'Jupe', 'Robe', 'Costume', 'Manteau', 'Autre'], params[:category]), include_blank: 'Sélectionner une catégorie', class: 'color-input' %>
    <%= select_tag :size, options_for_select(['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'], params[:size]), include_blank: 'Sélectionner une taille', class: 'color-input' %>
    <%= select_tag :couleurs, options_for_select(['Rouge', 'Bleu', 'Jaune', 'Vert', 'Blanc', 'Noir', 'Gris', 'Orange', 'Violet', 'Marron'], params[:couleurs]), include_blank: 'Sélectionner une couleur', class: 'color-input' %>
    <%= select_tag :textile_type, options_for_select(['Laine', 'Coton', 'Soie', 'Lin', 'Synthétique', 'Plastique', 'Acier', 'Autre'], params[:textile_type]), include_blank: 'Préciser la matière', class: 'color-input' %>
    <%= submit_tag 'Filtrer', class: 'dropdown-button-2' %>
  <% end %>
               
</div>
<h4 class = "p-4 text-center">Toutes les annonces</h4>
<div class="cards colored-border-top">
  <% @products.each do |product| %>
      <div class="card">
        <%= link_to product_bookmarks_path(product), data: { 'turbo-method'=> :post }, class: 'add-to-favorites-button' do %>
          <% if product.bookmarks.where(user: current_user).exists? %>
            <i class="fa-solid fa-heart favorite-icon favorite-active"></i>
          <% else %>
            <i class="fa-solid fa-heart favorite-icon"></i>
            <% end %>
        <% end %>
    <%= link_to product_path(product), class: "full-w" do %>
        <% if product.image.nil? %>
          <% product.image = "placeholder.jpg" %>
          <%= image_tag(product.image, alt: product.title) %>
        <% else %>
          <%= image_tag(product.image, alt: product.title) %>
        <% end %>
        <div class="card-info">
          <h2 class ="product-style"><%= product.title %></h2>
          <p class="description"><%= product.description %></p>
          <p class = "size-style">Taille : <%= product.size %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/my_index.html.erb
<% if @products.length == 0 %>
  <h4 class = "p-5 text-center">Mes produits</h4>
  <div class="cards colored-border-top">
    <p class="text-center">Vous n'avez pas encore publié de produits</p>
  </div>
  <div class ="d-flex justify-center">
  <%= link_to "Ajouter un produit", new_product_path, class: 'resa-button mx-auto text-center' %>
  </div>
  <%# <%= link_to "Modifier", edit_product_path(@product), class: "resa-button mx-auto text-center" %> 
<% end %>


<div class="cards colored-border-top">
  <% @products.each do |product| %>
      <div class="card">
    <%= link_to product_path(product), class: "full-w" do %>
        <% if product.image.nil? %>
          <% product.image = "placeholder.jpg" %>
          <%= image_tag(product.image, alt: product.title) %>
        <% else %>
          <%= image_tag(product.image, alt: product.title) %>
        <% end %>
        <div class="card-info">
          <h2 class ="product-style"><%= product.title %></h2>
          <p class="description"><%= product.description %></p>
          <p class = "size-style">Taille : <%= product.size %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<div id="edit_container" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="text-center">
        <%= simple_form_for @product, html: { class: "mt-3" } do |form| %>
          <div class="row">
            <%= form.input :title, label: "Titre" %>
            <%= form.input :description, label: "Description" %>
            <%= form.input :price, label: "Prix" %>


            <%= form.input :category, label: "Catégorie" do  %>
                <%= form.collection_select :category, ['Sport', 'Déguisement', 'Pantalon', 'Jupe', 'Robe', 'Costume', 'Manteau', 'Autre'], :to_s, :to_s, prompt: 'Sélectionner une catégorie' %>
  <% end %>
            <%= form.input :size, label: "Taille" do %>
              <%= form.collection_select :size, %w[XS S M L XL XXL XXXL], :to_s, :to_s, prompt: 'Sélectionner une taille' %>
            <% end %>
  <%= form.input :sexe, label: "Genre" do %>
    <%= form.collection_select :sexe, ['Homme', 'Femme', 'Enfant'], :to_s, :to_s, prompt: 'Sélectionner un genre' %>
  <% end %>
  <%= form.input :couleurs do %>
    <%= form.collection_select :couleurs, %w[Rouge Bleu Jaune Vert Blanc Noir Gris Autre], :to_s, :to_s, prompt: 'Sélectionner une couleur' %>
  <% end %>
  <%= form.input :textile_type, label: "Matière" do %>
    <%= form.collection_select :textile_type, %w[Laine Coton Soie Lin Synthétique Plastique Acier Autre], :to_s, :to_s, prompt: 'Sélectionner un type de textile' %>
  <% end %>
  </div>
            <div class="col-12">
              <%= form.button :submit, "Ajouter votre produit", class: "resa-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% if @product.image == nil %>
<div id = "main_container" class="container mt-5">
    <div class="col-8 mx-auto">
  <div class="row">
    <!-- Grande photo (col-6) -->
    <div class="col-12 col-md-6 mt-3 mb-3">
      <%= image_tag "placeholder.jpg", class: "img-fluid product_images", alt: "Large Photo" %>
    </div>

    <!-- Quatre petites photos (col-6) formant deux lignes de deux -->
    <div class="col-12 col-md-6">
      <div class="row">
        <div class="col-6 mt-3 mb-3">
          <%= image_tag "placeholder.jpg", class: "img-fluid product_images", alt: "Small Photo 1" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag "placeholder.jpg", class: "img-fluid product_images", alt: "Small Photo 2" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag "placeholder.jpg", class: "img-fluid product_images", alt: "Small Photo 3" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag "placeholder.jpg", class: "img-fluid product_images", alt: "Small Photo 4" %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div id = "main_container" class="container mt-5">
    <div class="col-8 mx-auto">
  <div class="row">
    <!-- Grande photo (col-6) -->
    <div class="col-12 col-md-6 mt-3 mb-3">
      <%= image_tag @product.image, class: "img-fluid product_images w-100 h-100", alt: "Large Photo" %>
    </div>

    <!-- Quatre petites photos (col-6) formant deux lignes de deux -->
    <div class="col-12 col-md-6">
      <div class="row">
        <div class="col-6 mt-3 mb-3">
          <%= image_tag @product.image, class: "img-fluid product_images", alt: "Small Photo 1" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag @product.image, class: "img-fluid product_images", alt: "Small Photo 2" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag @product.image, class: "img-fluid product_images", alt: "Small Photo 3" %>
        </div>
        <div class="col-6 mt-3 mb-3">
          <%= image_tag @product.image, class: "img-fluid product_images", alt: "Small Photo 4" %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="container mt-5">
    <div class="col-10 mx-auto">
<div class="mt-3">
  <div class = "row">
    <div class="col-6 pe-5">
  <h1 class="pb-3 colored-border-bottom"><%= @product.title %></h1>
  <p><%= @product.description %></p>
  <div class="d-flex justify-content-end p-2">
    <h5>Taille : <%= @product.size %></h5>
    <p></p>
  </div>

</div>
    <% if current_user && current_user.id == @product.user_id %>
        <div class = "col-6 reservation-box ps-5">
          <div class="row justify-content-center">
            <div class="text-center d-flex justify-content-center">
            <h3><%= @product.price %>€</h3> <p class ="p-1"> par jour</p>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-12">
              <div class="text-center d-flex justify-content-center">
          <h6>Ceci est votre article.</h6>
          </div>
          </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-6 ps-5">
              <div class="text-center d-flex justify-content-center">
            <%= link_to "Modifier", edit_product_path(@product), class: "resa-button mx-auto text-center" %>
            </div>
            </div>
            <div class="col-6">
              <div class="text-center d-flex justify-content-center">
            <%= link_to 'Supprimer', delete_product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button mx-auto text-center" %>
            </div>
            </div>
            </div>
          </div>
    <% else %>
      <div class = "col-6 reservation-box">
            <div class="row justify-content-center">
            <div class="text-center d-flex justify-content-center">
            <h3><%= @product.price %>€</h3> <p class ="p-1"> par jour</p>
            </div>
          </div>
          <%= render 'booking-form' %>
      </div>
    <% end %>
  </div>
</div>
  </div>
</div>