config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"

  root to: "products#index"
  get '/my_products', to: 'products#my_index', as: :my_products
  resources :products, only: [:destroy], as: :delete_products
  resources :products, except: [:destroy] do
    resources :bookmarks, only: [:new, :create] #maybe destroy?

  end
  resources :bookings, only: [:new, :create, :destroy, :edit, :index]
  resources :users, only: [:index] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:index]
    resources :bookmarks, only: [:destroy], as: :delete_bookmarks
  end
end

app/views/layouts/_navbar.html.erb
<!-- Navbar principale avec espaces en haut et en bas -->
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="padding-top: 20px; padding-bottom: 20px; padding-left: 20px; padding-right: 20px;">
  <div class="container-fluid">
    <!-- Logo "Iconic" à gauche -->
    <%# <div class="navbar-brand">
    </div> %>

    <!-- Bouton de basculement pour les écrans de petite taille -->

    <%= link_to "Iconic", root_path, class: "navbar-brand", aria: { current: "page" }%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <!-- Vos autres éléments de navigation ici -->
        </ul>
    </div>



    <!-- Contenu de la navbar lorsqu'elle est déployée -->
    <div class="collapse navbar-collapse ml-auto" id="navbarTogglerDemo03">
      <ul class="navbar-nav">

        <!-- Lien vers new product (Changement : Ajout du texte de description) -->
        <li class="nav-item">
          <%= link_to new_product_path, class: "nav-link" do %>
            <%= tag.i(class: "fa-solid fa-circle-plus icon") %>
            <span class="icon-text">Nouveau produit</span> <!-- Ajout du texte de description -->
          <% end %>
        </li>
        <!-- Lien vers "Mes réservations" (Changement : Ajout du texte de description) -->
        <li class="nav-item">
          <%= link_to bookings_path, class: "nav-link active", aria: { current: "page" } do %>
            <%= tag.i(class: "fa-solid fa-calendar icon") %>
            <span class="icon-text">Mes réservations</span> <!-- Ajout du texte de description -->
          <% end %>
        </li>
        <!-- Lien vers "Mes favoris" (si l'utilisateur est connecté) (Changement : Ajout du texte de description) -->
        <% if current_user %>
          <li class="nav-item">
            <%= link_to user_bookmarks_path(current_user.id), class: "nav-link active", aria: { current: "page" } do%>
              <%= tag.i(class: "fa-solid fa-heart icon") %>
              <span class="icon-text">Mes favoris</span> <!-- Ajout du texte de description -->
            <% end %>
          </li>
        <% end %>

      </ul>





      <!-- Barre de recherche centrée -->
      <form class="d-flex mx-auto" role="search" method="get" action="<%= root_path %>">
        <input class="form-control me-2" type="search" name="query" placeholder="Rechercher" aria-label="Rechercher">
        <button class="btn btn-outline search-btn-navbar" type="submit">Rechercher</button>
      </form>

      <!-- Menu déroulant à droite (Changement : Correction de la structure HTML) -->
      <div class="nav-item dropdown ml-auto">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <!-- Nom d'utilisateur (si connecté) -->
            <ul><%= current_user.username %></ul>
            <!-- Lien de déconnexion (si connecté) -->
            <ul><%= link_to 'Se déconnecter', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'devise_decorations' %></ul>
          <% else %>
            <!-- Lien de connexion (si non connecté) -->
            <%= link_to 'Se connecter', new_user_session_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<!-- Rendu des messages flash -->
<%= render "shared/flashes" %>

app/views/layouts/_navbar2.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg bg-body-tertiary navig-style">
    <%= link_to root_path, class: "navbar-brand", aria: { current: "page" } do %>
      Iconic
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Lien vers new product -->
        <li class="nav-item">
          <%= link_to new_product_path, class: "nav-link" do %>
            <%= tag.i(class: "fa-solid fa-circle-plus icon icone-style") %>
            <span class="icon-text">Nouveau produit</span>
          <% end %>
        </li>
        <!-- Lien vers "Mes réservations" -->
        <li class="nav-item">
          <%= link_to bookings_path, class: "nav-link active", aria: { current: "page" } do %>
            <%= tag.i(class: "fa-solid fa-calendar icon icone-style") %>
            <span class="icon-text">Mes réservations</span>
          <% end %>
        </li>
        <!-- Lien vers "Mes favoris" (si l'utilisateur est connecté) -->
        <% if current_user %>
          <li class="nav-item">
            <%= link_to user_bookmarks_path(current_user.id), class: "nav-link active", aria: { current: "page" } do%>
              <%= tag.i(class: "fa-solid fa-heart icon icone-style") %>
              <span class="icon-text">Mes favoris</span>
            <% end %>
          </li>
        <% end %>
      </ul>


      <!-- Barre de recherche et bouton de recherche -->
      <form class="d-flex ms-auto" role="search" method="get" action="<%= root_path %>">
        <input class="form-control me-2" type="search" name="query" placeholder="Rechercher" aria-label="Rechercher">
        <button class="btn btn-outline search-btn-navbar me-2" type="submit">Rechercher</button>
      </form>
      <!-- Menu déroulant à droite -->
      <div class="nav-item dropdown">
        <a href="#" class="avatar pl-2" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
        </a>
        <div class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <!-- Nom d'utilisateur (si connecté) -->
            <ul class="list-unstyled"><%= current_user.username %></ul>
            <!-- Lien de déconnexion (si connecté) -->
            <ul class="list-unstyled"><%= link_to 'Mes produits', my_products_path, class: 'devise_decorations' %></ul>
            <ul class="list-unstyled"><%= link_to 'Se déconnecter', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'devise_decorations' %></ul>
          <% else %>

            <!-- Lien de connexion (si non connecté) -->
            <%= link_to 'Se connecter', new_user_session_path, class: 'devise_decorations' %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</div>